import os

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_DIR   = os.path.join(BASE_DIR, 'downloads')
OUTPUT_DIR     = os.path.join(BASE_DIR, 'output')
EXTRACTOR_DIR  = os.path.join(BASE_DIR, 'extractor')
STATE_FILE     = os.path.join(BASE_DIR, 'state.json')

# ── Source ────────────────────────────────────────────────────────────────────
BASE_URL  = 'https://www.jp-life.japanpost.jp'
INDEX_URL = 'https://www.jp-life.japanpost.jp/english/news/en_news_index.html'

# ── Browser ───────────────────────────────────────────────────────────────────
HEADLESS_MODE = True
WAIT_TIMEOUT  = 60

# ── Run options ───────────────────────────────────────────────────────────────
BYPASS_CACHE  = False   # True = re-download even if release already processed
RELEASE_YEAR  = None    # None = always pick latest Financial Results; int = specific year e.g. 2026
RELEASE_DATE  = None    # None = use RELEASE_YEAR logic; str = exact date e.g. 'May 15, 2025'

# ── Output ────────────────────────────────────────────────────────────────────
DATASET_CODE = 'PICQD'

# ── Column codes (absolute, in order) ─────────────────────────────────────────
COLUMN_CODES = [
    # Unaudited Non-Consolidated Balance Sheets — 42 cols
    'PICQD.UNONCONSBS.ASSET.CASHDEP.Q',
    'PICQD.UNONCONSBS.ASSET.CASHDEP.CASH.Q',
    'PICQD.UNONCONSBS.ASSET.CASHDEP.DEP.Q',
    'PICQD.UNONCONSBS.ASSET.CALLOAN.Q',
    'PICQD.UNONCONSBS.ASSET.RECRESAGREE.Q',
    'PICQD.UNONCONSBS.ASSET.RECSECBORTRANS.Q',
    'PICQD.UNONCONSBS.ASSET.MONCLAIMBOU.Q',
    'PICQD.UNONCONSBS.ASSET.MONHELD.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.JGOVBOND.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.JLOCGOVBOND.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.JCORPBOND.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.STOCK.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.FORSEC.Q',
    'PICQD.UNONCONSBS.ASSET.SEC.OTHER.Q',
    'PICQD.UNONCONSBS.ASSET.LOAN.Q',
    'PICQD.UNONCONSBS.ASSET.LOAN.POLLOAN.Q',
    'PICQD.UNONCONSBS.ASSET.LOAN.INDCOMLOAN.Q',
    'PICQD.UNONCONSBS.ASSET.LOAN.LOANMANNET.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.LAND.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.BUILD.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.LEASAS.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.CONSPROG.Q',
    'PICQD.UNONCONSBS.ASSET.TANFIX.OTHER.Q',
    'PICQD.UNONCONSBS.ASSET.INTFIXAS.Q',
    'PICQD.UNONCONSBS.ASSET.INTFIXAS.SOFT.Q',
    'PICQD.UNONCONSBS.ASSET.INTFIXAS.OTHER.Q',
    'PICQD.UNONCONSBS.ASSET.AGACCREC.Q',
    'PICQD.UNONCONSBS.ASSET.REINREC.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.ACREC.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.PREEXP.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.ACINC.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.MONDEP.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.DERFININS.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.CAHCOLPAID.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.SUSPAY.Q',
    'PICQD.UNONCONSBS.ASSET.OTHER.OTHER.Q',
    'PICQD.UNONCONSBS.ASSET.DEFTAXAS.Q',
    'PICQD.UNONCONSBS.ASSET.RESPOSLOAN.Q',
    'PICQD.UNONCONSBS.ASSET.TOTAL.Q',
    # Unaudited Consolidated Balance Sheets — 23 cols
    'PICQD.UCONSBS.ASSET.CASHDEP.Q',
    'PICQD.UCONSBS.ASSET.CALLOAN.Q',
    'PICQD.UCONSBS.ASSET.RECRESAGREE.Q',
    'PICQD.UCONSBS.ASSET.RECUNSEC.Q',
    'PICQD.UCONSBS.ASSET.MONCLAIM.Q',
    'PICQD.UCONSBS.ASSET.MONHELD.Q',
    'PICQD.UCONSBS.ASSET.SEC.Q',
    'PICQD.UCONSBS.ASSET.LOAN.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.LAND.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.BUILD.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.LEASAS.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.CONSPROG.Q',
    'PICQD.UCONSBS.ASSET.TANFIX.OTHER.Q',
    'PICQD.UCONSBS.ASSET.INTFIX.Q',
    'PICQD.UCONSBS.ASSET.INTFIX.SOFT.Q',
    'PICQD.UCONSBS.ASSET.INTFIX.OTHER.Q',
    'PICQD.UCONSBS.ASSET.AGACREC.Q',
    'PICQD.UCONSBS.ASSET.REINREC.Q',
    'PICQD.UCONSBS.ASSET.OTHER.Q',
    'PICQD.UCONSBS.ASSET.DEFTAX.Q',
    'PICQD.UCONSBS.ASSET.RESPOSLOAN.Q',
    'PICQD.UCONSBS.ASSET.TOTAL.Q',
    # Fair Values of Financial Instruments — 34 cols
    'PICQD.FAIRVAL.ASSET.CONS.CASHDEP.Q',
    'PICQD.FAIRVAL.ASSET.CONS.CASHDEP.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.CONS.CALLOAN.Q',
    'PICQD.FAIRVAL.ASSET.CONS.RECUNSEC.Q',
    'PICQD.FAIRVAL.ASSET.CONS.MONCLAIM.Q',
    'PICQD.FAIRVAL.ASSET.CONS.MONCLAIM.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.CONS.MONHELD.Q',
    'PICQD.FAIRVAL.ASSET.CONS.SEC.Q',
    'PICQD.FAIRVAL.ASSET.CONS.SEC.HELDMAT.Q',
    'PICQD.FAIRVAL.ASSET.CONS.SEC.POLRESBOND.Q',
    'PICQD.FAIRVAL.ASSET.CONS.SEC.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.CONS.LOAN.Q',
    'PICQD.FAIRVAL.ASSET.CONS.LOAN.POLLOAN.Q',
    'PICQD.FAIRVAL.ASSET.CONS.LOAN.INDCOMLOAN.Q',
    'PICQD.FAIRVAL.ASSET.CONS.LOAN.LOANMANNET.Q',
    'PICQD.FAIRVAL.ASSET.CONS.LOAN.RESPOSLOAN.Q',
    'PICQD.FAIRVAL.ASSET.CONS.TOTAL.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.CASHDEP.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.CASHDEP.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.CALLOAN.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.RECUNSEC.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.MONCLAIM.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.MONCLAIM.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.MONHELD.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.SEC.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.SEC.HELDMAT.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.SEC.POLRESBOND.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.SEC.AVSALSEC.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.LOAN.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.LOAN.POLLOAN.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.LOAN.INDCOMLOAN.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.LOAN.LOANMANNET.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.LOAN.RESPOSLOAN.Q',
    'PICQD.FAIRVAL.ASSET.FAIRVAL.TOTAL.Q',
    # Held-to-maturity Bonds — 24 cols
    'PICQD.HELDMAT.CONS.EXCEED.BOND.Q',
    'PICQD.HELDMAT.CONS.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.HELDMAT.CONS.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.HELDMAT.CONS.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.HELDMAT.CONS.EXCEED.FORSEC.Q',
    'PICQD.HELDMAT.CONS.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.BOND.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.FORSEC.Q',
    'PICQD.HELDMAT.FAIRVAL.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.BOND.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.FORSEC.Q',
    'PICQD.HELDMAT.CONS.NOTEXC.FORSEC.FORBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.BOND.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.FORSEC.Q',
    'PICQD.HELDMAT.FAIRVAL.NOTEXC.FORSEC.FORBOND.Q',
    # Policy-reserve-matching Bonds — 24 cols
    'PICQD.POLRES.CONS.EXCEED.BOND.Q',
    'PICQD.POLRES.CONS.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.POLRES.CONS.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.POLRES.CONS.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.POLRES.CONS.EXCEED.FORSEC.Q',
    'PICQD.POLRES.CONS.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.BOND.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.FORSEC.Q',
    'PICQD.POLRES.FAIRVAL.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.POLRES.CONS.NOTEXC.BOND.Q',
    'PICQD.POLRES.CONS.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.POLRES.CONS.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.POLRES.CONS.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.POLRES.CONS.NOTEXC.FORSEC.Q',
    'PICQD.POLRES.CONS.NOTEXC.FORSEC.FORBOND.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.BOND.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.FORSEC.Q',
    'PICQD.POLRES.FAIRVAL.NOTEXC.FORSEC.FORBOND.Q',
    # Available-for-sale Securities — 36 cols
    'PICQD.ASALSEC.CONS.EXCEED.BOND.Q',
    'PICQD.ASALSEC.CONS.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.ASALSEC.CONS.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.ASALSEC.CONS.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.ASALSEC.CONS.EXCEED.STOCK.Q',
    'PICQD.ASALSEC.CONS.EXCEED.FORSEC.Q',
    'PICQD.ASALSEC.CONS.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.ASALSEC.CONS.EXCEED.FORSEC.OTHER.Q',
    'PICQD.ASALSEC.CONS.EXCEED.OTHER.Q',
    'PICQD.ASALSEC.COST.EXCEED.BOND.Q',
    'PICQD.ASALSEC.COST.EXCEED.BOND.JGOVBOND.Q',
    'PICQD.ASALSEC.COST.EXCEED.BOND.JLOCGOVBOND.Q',
    'PICQD.ASALSEC.COST.EXCEED.BOND.JCORPBOND.Q',
    'PICQD.ASALSEC.COST.EXCEED.STOCK.Q',
    'PICQD.ASALSEC.COST.EXCEED.FORSEC.Q',
    'PICQD.ASALSEC.COST.EXCEED.FORSEC.FORBOND.Q',
    'PICQD.ASALSEC.COST.EXCEED.FORSEC.OTHER.Q',
    'PICQD.ASALSEC.COST.EXCEED.OTHER.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.BOND.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.STOCK.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.FORSEC.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.FORSEC.FORBOND.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.FORSEC.OTHER.Q',
    'PICQD.ASALSEC.CONS.NOTEXC.OTHER.Q',
    'PICQD.ASALSEC.COST.NOTEXC.BOND.Q',
    'PICQD.ASALSEC.COST.NOTEXC.BOND.JGOVBOND.Q',
    'PICQD.ASALSEC.COST.NOTEXC.BOND.JLOCGOVBOND.Q',
    'PICQD.ASALSEC.COST.NOTEXC.BOND.JCORPBOND.Q',
    'PICQD.ASALSEC.COST.NOTEXC.STOCK.Q',
    'PICQD.ASALSEC.COST.NOTEXC.FORSEC.Q',
    'PICQD.ASALSEC.COST.NOTEXC.FORSEC.FORBOND.Q',
    'PICQD.ASALSEC.COST.NOTEXC.FORSEC.OTHER.Q',
    'PICQD.ASALSEC.COST.NOTEXC.OTHER.Q',
    # Money held in trust classified as other than trading — 2 cols
    'PICQD.MONHELD.CONS.SPECMONHELD.Q',
    'PICQD.MONHELD.COST.SPECMONHELD.Q',
    # Currency-related derivatives — 12 cols
    'PICQD.CURRELDER.CONTR.SOLD.Q',
    'PICQD.CURRELDER.CONTR.SOLD.USD.Q',
    'PICQD.CURRELDER.CONTR.SOLD.EUR.Q',
    'PICQD.CURRELDER.CONTR.SOLD.AUD.Q',
    'PICQD.CURRELDER.CONTR.SOLD.OTHER.Q',
    'PICQD.CURRELDER.CONTR.TOTAL.Q',
    'PICQD.CURRELDER.FAIRVAL.SOLD.Q',
    'PICQD.CURRELDER.FAIRVAL.SOLD.USD.Q',
    'PICQD.CURRELDER.FAIRVAL.SOLD.EUR.Q',
    'PICQD.CURRELDER.FAIRVAL.SOLD.AUD.Q',
    'PICQD.CURRELDER.FAIRVAL.SOLD.OTHER.Q',
    'PICQD.CURRELDER.FAIRVAL.TOTAL.Q',
    # Interest rate-related derivatives — 4 cols
    'PICQD.INTRATEDER.CONTR.DEFHEDGE.Q',
    'PICQD.INTRATEDER.CONTR.EXCTREATINT.Q',
    'PICQD.INTRATEDER.FAIRVAL.DEFHEDGE.Q',
    'PICQD.INTRATEDER.FAIRVAL.EXCTREATINT.Q',
    # Available-for-sale Securities Sold during the Fiscal Year — 24 cols
    'PICQD.ASALSECSOLD.SAL.BOND.Q',
    'PICQD.ASALSECSOLD.SAL.BOND.JGOVBOND.Q',
    'PICQD.ASALSECSOLD.SAL.BOND.JCORBOND.Q',
    'PICQD.ASALSECSOLD.SAL.STOCK.Q',
    'PICQD.ASALSECSOLD.SAL.FORSEC.Q',
    'PICQD.ASALSECSOLD.SAL.FORSEC.FORBOND.Q',
    'PICQD.ASALSECSOLD.SAL.FORSEC.OTHER.Q',
    'PICQD.ASALSECSOLD.SAL.OTHER.Q',
    'PICQD.ASALSECSOLD.GAIN.BOND.Q',
    'PICQD.ASALSECSOLD.GAIN.BOND.JGOVBOND.Q',
    'PICQD.ASALSECSOLD.GAIN.BOND.JCORBOND.Q',
    'PICQD.ASALSECSOLD.GAIN.STOCK.Q',
    'PICQD.ASALSECSOLD.GAIN.FORSEC.Q',
    'PICQD.ASALSECSOLD.GAIN.FORSEC.FORBOND.Q',
    'PICQD.ASALSECSOLD.GAIN.FORSEC.OTHER.Q',
    'PICQD.ASALSECSOLD.GAIN.OTHER.Q',
    'PICQD.ASALSECSOLD.LOS.BOND.Q',
    'PICQD.ASALSECSOLD.LOS.BOND.JGOVBOND.Q',
    'PICQD.ASALSECSOLD.LOS.BOND.JCORBOND.Q',
    'PICQD.ASALSECSOLD.LOS.STOCK.Q',
    'PICQD.ASALSECSOLD.LOS.FORSEC.Q',
    'PICQD.ASALSECSOLD.LOS.FORSEC.FORBOND.Q',
    'PICQD.ASALSECSOLD.LOS.FORSEC.OTHER.Q',
    'PICQD.ASALSECSOLD.LOS.OTHER.Q',
    # Assets held-to-maturity in trust — 3 cols
    'PICQD.AHELDMAT.BOOK.AHELDTOM.Q',
    'PICQD.AHELDMAT.BOOK.AHELDRES.Q',
    'PICQD.AHELDMAT.BOOK.OTHERMONHELD.Q',
]

# ── Column descriptions (absolute, in order — matches COLUMN_CODES 1:1) ───────
COLUMN_HEADERS = [
    # Unaudited Non-Consolidated Balance Sheets
    'Unaudited Non-Consolidated Balance Sheets: Assets: Cash and deposits',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Cash and deposits: Cash',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Cash and deposits: Deposits',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Call loans',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Receivables under resale agreements ',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Receivables under securities borrowing transactions',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Monetary claims bought',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Money held in trust',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Japanese government bonds',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Japanese local government bond',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Japanese corporate bonds',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Stocks',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Foreign securities',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Securities: Other securities',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Loans',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Loans: Policy loans',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Loans: Industrial and commercial loans',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Loans: Loans to the Management Network',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets: Land',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets: Buildings',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets: Leased assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets: Construction in progress',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Tangible fixed assets: Other tangible fixed assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Intangible fixed assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Intangible fixed assets: Software',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Intangible fixed assets: Other intangible fixed assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Agency accounts receivable',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Reinsurance receivables',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Accounts receivable',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Prepaid expenses',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Accrued income',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Money on deposit',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Derivative financial instruments',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Cash collateral paid for financial instruments',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Suspense payments',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Other assets: Other assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Deferred tax assets',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Reserve for possible loan losses',
    'Unaudited Non-Consolidated Balance Sheets: Assets: Total',
    # Unaudited Consolidated Balance Sheets
    'Unaudited Consolidated Balance Sheets: Assets: Cash and deposits',
    'Unaudited Consolidated Balance Sheets: Assets: Call loans',
    'Unaudited Consolidated Balance Sheets: Assets: Receivables under resale agreements ',
    'Unaudited Consolidated Balance Sheets: Assets: Receivables under securities borrowing transactions',
    'Unaudited Consolidated Balance Sheets: Assets: Monetary claims bought',
    'Unaudited Consolidated Balance Sheets: Assets: Money held in trust',
    'Unaudited Consolidated Balance Sheets: Assets: Securities',
    'Unaudited Consolidated Balance Sheets: Assets: Loans',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets: Land',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets: Buildings',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets: Leased assets',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets: Construction in progress',
    'Unaudited Consolidated Balance Sheets: Assets: Tangible fixed assets: Other tangible fixed assets',
    'Unaudited Consolidated Balance Sheets: Assets: Intangible fixed assets',
    'Unaudited Consolidated Balance Sheets: Assets: Intangible fixed assets: Software',
    'Unaudited Consolidated Balance Sheets: Assets: Intangible fixed assets: Other intangible fixed assets',
    'Unaudited Consolidated Balance Sheets: Assets: Agency accounts receivable',
    'Unaudited Consolidated Balance Sheets: Assets: Reinsurance receivables',
    'Unaudited Consolidated Balance Sheets: Assets: Other assets',
    'Unaudited Consolidated Balance Sheets: Assets: Deferred tax assets',
    'Unaudited Consolidated Balance Sheets: Assets: Reserve for possible loan losses',
    'Unaudited Consolidated Balance Sheets: Assets: Total',
    # Fair Values of Financial Instruments
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Cash and deposits',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Cash and deposits: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Call loans',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Receivables under securities borrowing transactions',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Monetary claims bought',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Monetary claims bought: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Money held in trust',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Securities',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Securities: Held-to-maturity bonds',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Securities: Policy-reserve-matching bonds',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Securities: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Loans',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Loans: Policy loans',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Loans: Industrial and commercial loans',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Loans: Loans to the Management Network',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Loans: Reserve for possible loan losses',
    'Fair Values of Financial Instruments: Assets: Consolidated balance sheet amount: Total',
    'Fair Values of Financial Instruments: Assets: Fair value: Cash and deposits',
    'Fair Values of Financial Instruments: Assets: Fair value: Cash and deposits: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Fair value: Call loans',
    'Fair Values of Financial Instruments: Assets: Fair value: Receivables under securities borrowing transactions',
    'Fair Values of Financial Instruments: Assets: Fair value: Monetary claims bought',
    'Fair Values of Financial Instruments: Assets: Fair value: Monetary claims bought: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Fair value: Money held in trust',
    'Fair Values of Financial Instruments: Assets: Fair value: Securities',
    'Fair Values of Financial Instruments: Assets: Fair value: Securities: Held-to-maturity bonds',
    'Fair Values of Financial Instruments: Assets: Fair value: Securities: Policy-reserve-matching bonds',
    'Fair Values of Financial Instruments: Assets: Fair value: Securities: Available-for-sale securities',
    'Fair Values of Financial Instruments: Assets: Fair value: Loans',
    'Fair Values of Financial Instruments: Assets: Fair value: Loans: Policy loans',
    'Fair Values of Financial Instruments: Assets: Fair value: Loans: Industrial and commercial loans',
    'Fair Values of Financial Instruments: Assets: Fair value: Loans: Loans to the Management Network',
    'Fair Values of Financial Instruments: Assets: Fair value: Loans: Reserve for possible loan losses',
    'Fair Values of Financial Instruments: Assets: Fair value: Total',
    # Held-to-maturity Bonds
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Held-to-maturity Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Held-to-maturity Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Held-to-maturity Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    # Policy-reserve-matching Bonds
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Policy-reserve-matching Bonds: Fair value: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Policy-reserve-matching Bonds: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Policy-reserve-matching Bonds: Fair value: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    # Available-for-sale Securities
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Stocks',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Other',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value exceeds the consolidated balance sheet amount: Other',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Bonds',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Stocks',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Foreign securities',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Foreign securities: Other',
    'Available-for-sale Securities: Cost: Fair value exceeds the consolidated balance sheet amount: Other',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Stocks',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Other',
    'Available-for-sale Securities: Consolidated balance sheet amount: Fair value does not exceed the consolidated balance sheet amount: Other',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Bonds',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese government bonds',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese local government bonds',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Stocks',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Foreign securities',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Foreign bonds',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Foreign securities: Other',
    'Available-for-sale Securities: Cost: Fair value does not exceed the consolidated balance sheet amount: Other',
    # Money held in trust classified as other than trading
    'Money held in trust classified as other than trading: Consolidated balance sheet amount: Specified money held in trust',
    'Money held in trust classified as other than trading: Cost: Specified money held in trust',
    # Currency-related derivatives
    'Currency-related derivatives: Contract amount: Sold',
    'Currency-related derivatives: Contract amount: Sold: U.S. dollars',
    'Currency-related derivatives: Contract amount: Sold: Euros',
    'Currency-related derivatives: Contract amount: Sold: Australian dollars',
    'Currency-related derivatives: Contract amount: Sold: Other',
    'Currency-related derivatives: Contract amount: Total',
    'Currency-related derivatives: Fair value: Sold',
    'Currency-related derivatives: Fair value: Sold: U.S. dollars',
    'Currency-related derivatives: Fair value: Sold: Euros',
    'Currency-related derivatives: Fair value: Sold: Australian dollars',
    'Currency-related derivatives: Fair value: Sold: Other',
    'Currency-related derivatives: Fair value: Total',
    # Interest rate-related derivatives
    'Interest rate-related derivatives: Contract amount: Deferred hedge method',
    'Interest rate-related derivatives: Contract amount: Exceptional treatment for interest rate swaps',
    'Interest rate-related derivatives: Fair value: Deferred hedge method',
    'Interest rate-related derivatives: Fair value: Exceptional treatment for interest rate swaps',
    # Available-for-sale Securities Sold during the Fiscal Year
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Bonds: Japanese government bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Stocks',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Foreign securities: Foreign bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Foreign securities: Other foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Sales: Other securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Bonds: Japanese government bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Stocks',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Foreign securities: Foreign bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Foreign securities: Other foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Gains: Other securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Bonds: Japanese government bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Bonds: Japanese corporate bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Stocks',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Foreign securities: Foreign bonds',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Foreign securities: Other foreign securities',
    'Available-for-sale Securities Sold during the Fiscal Year: Losses: Other securities',
    # Assets held-to-maturity in trust
    'Assets held-to-maturity in trust/assets held for reserves in trust: Book value: Assets held-tomaturity in trust',
    'Assets held-to-maturity in trust/assets held for reserves in trust: Book value: Assets held for reserves in trust',
    'Assets held-to-maturity in trust/assets held for reserves in trust: Book value: Other money held in trust',
]

assert len(COLUMN_CODES) == len(COLUMN_HEADERS), (
    f"Mismatch: {len(COLUMN_CODES)} codes vs {len(COLUMN_HEADERS)} headers"
)

# ── Table: Non-Consolidated Balance Sheet — label → column code suffix ────────
# Ordered list; positional match against camelot-extracted labels.
# Labels that appear twice (e.g. "Other assets") are matched first-occurrence first.
UNONCONSBS_LABELS = [
    ('Cash and deposits',                                     'ASSET.CASHDEP.Q'),
    ('Cash',                                                  'ASSET.CASHDEP.CASH.Q'),
    ('Deposits',                                              'ASSET.CASHDEP.DEP.Q'),
    ('Call loans',                                            'ASSET.CALLOAN.Q'),
    ('Receivables under resale agreements',                   'ASSET.RECRESAGREE.Q'),
    ('Receivables under securities borrowing transactions',   'ASSET.RECSECBORTRANS.Q'),
    ('Monetary claims bought',                                'ASSET.MONCLAIMBOU.Q'),
    ('Money held in trust',                                   'ASSET.MONHELD.Q'),
    ('Securities',                                            'ASSET.SEC.Q'),
    ('Japanese government bonds',                             'ASSET.SEC.JGOVBOND.Q'),
    ('Japanese local government bonds',                       'ASSET.SEC.JLOCGOVBOND.Q'),
    ('Japanese corporate bonds',                              'ASSET.SEC.JCORPBOND.Q'),
    ('Stocks',                                                'ASSET.SEC.STOCK.Q'),
    ('Foreign securities',                                    'ASSET.SEC.FORSEC.Q'),
    ('Other securities',                                      'ASSET.SEC.OTHER.Q'),
    ('Loans',                                                 'ASSET.LOAN.Q'),
    ('Policy loans',                                          'ASSET.LOAN.POLLOAN.Q'),
    ('Industrial and commercial loans',                       'ASSET.LOAN.INDCOMLOAN.Q'),
    ('Loans to the Management Network',                       'ASSET.LOAN.LOANMANNET.Q'),
    ('Tangible fixed assets',                                 'ASSET.TANFIX.Q'),
    ('Land',                                                  'ASSET.TANFIX.LAND.Q'),
    ('Buildings',                                             'ASSET.TANFIX.BUILD.Q'),
    ('Leased assets',                                         'ASSET.TANFIX.LEASAS.Q'),
    ('Construction in progress',                              'ASSET.TANFIX.CONSPROG.Q'),
    ('Other tangible fixed assets',                           'ASSET.TANFIX.OTHER.Q'),
    ('Intangible fixed assets',                               'ASSET.INTFIXAS.Q'),
    ('Software',                                              'ASSET.INTFIXAS.SOFT.Q'),
    ('Other intangible fixed assets',                         'ASSET.INTFIXAS.OTHER.Q'),
    ('Agency accounts receivable',                            'ASSET.AGACCREC.Q'),
    ('Reinsurance receivables',                               'ASSET.REINREC.Q'),
    ('Other assets',                                          'ASSET.OTHER.Q'),          # first occurrence = section total
    ('Accounts receivable',                                   'ASSET.OTHER.ACREC.Q'),
    ('Prepaid expenses',                                      'ASSET.OTHER.PREEXP.Q'),
    ('Accrued income',                                        'ASSET.OTHER.ACINC.Q'),
    ('Money on deposit',                                      'ASSET.OTHER.MONDEP.Q'),
    ('Derivative financial instruments',                      'ASSET.OTHER.DERFININS.Q'),
    ('Cash collateral paid for financial instruments',        'ASSET.OTHER.CAHCOLPAID.Q'),
    ('Suspense payments',                                     'ASSET.OTHER.SUSPAY.Q'),
    ('Other assets',                                          'ASSET.OTHER.OTHER.Q'),    # second occurrence = sub-item
    ('Deferred tax assets',                                   'ASSET.DEFTAXAS.Q'),
    ('Reserve for possible loan losses',                      'ASSET.RESPOSLOAN.Q'),
    ('Total assets',                                          'ASSET.TOTAL.Q'),
]

# ── Table: Consolidated Balance Sheet — label → column code suffix ────────────
UCONSBS_LABELS = [
    ('Cash and deposits',                                     'ASSET.CASHDEP.Q'),
    ('Call loans',                                            'ASSET.CALLOAN.Q'),
    ('Receivables under resale agreements',                   'ASSET.RECRESAGREE.Q'),
    ('Receivables under securities borrowing transactions',   'ASSET.RECUNSEC.Q'),
    ('Monetary claims bought',                                'ASSET.MONCLAIM.Q'),
    ('Money held in trust',                                   'ASSET.MONHELD.Q'),
    ('Securities',                                            'ASSET.SEC.Q'),
    ('Loans',                                                 'ASSET.LOAN.Q'),
    ('Tangible fixed assets',                                 'ASSET.TANFIX.Q'),
    ('Land',                                                  'ASSET.TANFIX.LAND.Q'),
    ('Buildings',                                             'ASSET.TANFIX.BUILD.Q'),
    ('Leased assets',                                         'ASSET.TANFIX.LEASAS.Q'),
    ('Construction in progress',                              'ASSET.TANFIX.CONSPROG.Q'),
    ('Other tangible fixed assets',                           'ASSET.TANFIX.OTHER.Q'),
    ('Intangible fixed assets',                               'ASSET.INTFIX.Q'),
    ('Software',                                              'ASSET.INTFIX.SOFT.Q'),
    ('Other intangible fixed assets',                         'ASSET.INTFIX.OTHER.Q'),
    ('Agency accounts receivable',                            'ASSET.AGACREC.Q'),
    ('Reinsurance receivables',                               'ASSET.REINREC.Q'),
    ('Other assets',                                          'ASSET.OTHER.Q'),
    ('Deferred tax assets',                                   'ASSET.DEFTAX.Q'),
    ('Reserve for possible loan losses',                      'ASSET.RESPOSLOAN.Q'),
    ('Total assets',                                          'ASSET.TOTAL.Q'),
]

# ── Table: Fair Values of Financial Instruments — label → (cons_col, fv_col) ──
# Each entry: (label, consolidated_balance_sheet_col, fair_value_col)
FAIRVAL_LABELS = [
    ('Monetary claims bought',                   'FAIRVAL.ASSET.CONS.MONCLAIM.Q',        'FAIRVAL.ASSET.FAIRVAL.MONCLAIM.Q'),
    ('Available-for-sale securities',            'FAIRVAL.ASSET.CONS.MONCLAIM.AVSALSEC.Q','FAIRVAL.ASSET.FAIRVAL.MONCLAIM.AVSALSEC.Q'),
    ('Money held in trust',                      'FAIRVAL.ASSET.CONS.MONHELD.Q',         'FAIRVAL.ASSET.FAIRVAL.MONHELD.Q'),
    ('Securities',                               'FAIRVAL.ASSET.CONS.SEC.Q',             'FAIRVAL.ASSET.FAIRVAL.SEC.Q'),
    ('Held-to-maturity bonds',                   'FAIRVAL.ASSET.CONS.SEC.HELDMAT.Q',     'FAIRVAL.ASSET.FAIRVAL.SEC.HELDMAT.Q'),
    ('Policy-reserve-matching bonds',            'FAIRVAL.ASSET.CONS.SEC.POLRESBOND.Q',  'FAIRVAL.ASSET.FAIRVAL.SEC.POLRESBOND.Q'),
    ('Available-for-sale securities',            'FAIRVAL.ASSET.CONS.SEC.AVSALSEC.Q',    'FAIRVAL.ASSET.FAIRVAL.SEC.AVSALSEC.Q'),
    ('Loans',                                    'FAIRVAL.ASSET.CONS.LOAN.Q',            'FAIRVAL.ASSET.FAIRVAL.LOAN.Q'),
    ('Policy loans',                             'FAIRVAL.ASSET.CONS.LOAN.POLLOAN.Q',    'FAIRVAL.ASSET.FAIRVAL.LOAN.POLLOAN.Q'),
    ('Industrial and commercial loans',          'FAIRVAL.ASSET.CONS.LOAN.INDCOMLOAN.Q', 'FAIRVAL.ASSET.FAIRVAL.LOAN.INDCOMLOAN.Q'),
    ('Loans to the Management Network',          'FAIRVAL.ASSET.CONS.LOAN.LOANMANNET.Q', 'FAIRVAL.ASSET.FAIRVAL.LOAN.LOANMANNET.Q'),
    ('Reserve for possible loan losses',         'FAIRVAL.ASSET.CONS.LOAN.RESPOSLOAN.Q', 'FAIRVAL.ASSET.FAIRVAL.LOAN.RESPOSLOAN.Q'),
    ('Total assets',                             'FAIRVAL.ASSET.CONS.TOTAL.Q',           'FAIRVAL.ASSET.FAIRVAL.TOTAL.Q'),
]

# ── Tables: Held-to-maturity / Policy-reserve-matching Bonds ─────────────────
# Structure: {section_key: {label: col_suffix}}
# section_key: 'exceed' or 'notexc'
# col_suffix appended to 'PICQD.HELDMAT.' or 'PICQD.POLRES.'
BONDS_SEC_LABELS = {
    'exceed': [
        ('Bonds',                    'BOND.Q'),
        ('Japanese government bonds','BOND.JGOVBOND.Q'),
        ('Japanese local government bonds', 'BOND.JLOCGOVBOND.Q'),
        ('Japanese corporate bonds', 'BOND.JCORPBOND.Q'),
        ('Foreign securities',       'FORSEC.Q'),
        ('Foreign bonds',            'FORSEC.FORBOND.Q'),
    ],
    'notexc': [
        ('Bonds',                    'BOND.Q'),
        ('Japanese government bonds','BOND.JGOVBOND.Q'),
        ('Japanese local government bonds', 'BOND.JLOCGOVBOND.Q'),
        ('Japanese corporate bonds', 'BOND.JCORPBOND.Q'),
        ('Foreign securities',       'FORSEC.Q'),
        ('Foreign bonds',            'FORSEC.FORBOND.Q'),
    ],
}

# ── Table: Available-for-sale Securities ─────────────────────────────────────
# Structure: {section_key: {label: (cons_col, cost_col)}}
ASALSEC_LABELS = {
    'exceed': [
        ('Bonds',                    'CONS.EXCEED.BOND.Q',           'COST.EXCEED.BOND.Q'),
        ('Japanese government bonds','CONS.EXCEED.BOND.JGOVBOND.Q',  'COST.EXCEED.BOND.JGOVBOND.Q'),
        ('Japanese local government bonds', 'CONS.EXCEED.BOND.JLOCGOVBOND.Q','COST.EXCEED.BOND.JLOCGOVBOND.Q'),
        ('Japanese corporate bonds', 'CONS.EXCEED.BOND.JCORPBOND.Q','COST.EXCEED.BOND.JCORPBOND.Q'),
        ('Stocks',                   'CONS.EXCEED.STOCK.Q',          'COST.EXCEED.STOCK.Q'),
        ('Foreign securities',       'CONS.EXCEED.FORSEC.Q',         'COST.EXCEED.FORSEC.Q'),
        ('Foreign bonds',            'CONS.EXCEED.FORSEC.FORBOND.Q', 'COST.EXCEED.FORSEC.FORBOND.Q'),
        ('Other foreign securities', 'CONS.EXCEED.FORSEC.OTHER.Q',   'COST.EXCEED.FORSEC.OTHER.Q'),
        ('Other',                    'CONS.EXCEED.OTHER.Q',          'COST.EXCEED.OTHER.Q'),
    ],
    'notexc': [
        ('Bonds',                    'CONS.NOTEXC.BOND.Q',           'COST.NOTEXC.BOND.Q'),
        ('Japanese government bonds','CONS.NOTEXC.BOND.JGOVBOND.Q',  'COST.NOTEXC.BOND.JGOVBOND.Q'),
        ('Japanese local government bonds', 'CONS.NOTEXC.BOND.JLOCGOVBOND.Q','COST.NOTEXC.BOND.JLOCGOVBOND.Q'),
        ('Japanese corporate bonds', 'CONS.NOTEXC.BOND.JCORPBOND.Q','COST.NOTEXC.BOND.JCORPBOND.Q'),
        ('Stocks',                   'CONS.NOTEXC.STOCK.Q',          'COST.NOTEXC.STOCK.Q'),
        ('Foreign securities',       'CONS.NOTEXC.FORSEC.Q',         'COST.NOTEXC.FORSEC.Q'),
        ('Foreign bonds',            'CONS.NOTEXC.FORSEC.FORBOND.Q', 'COST.NOTEXC.FORSEC.FORBOND.Q'),
        ('Other foreign securities', 'CONS.NOTEXC.FORSEC.OTHER.Q',   'COST.NOTEXC.FORSEC.OTHER.Q'),
        ('Other',                    'CONS.NOTEXC.OTHER.Q',          'COST.NOTEXC.OTHER.Q'),
    ],
}

# ── Table: Available-for-sale Securities Sold during the Fiscal Year ──────────
# label → (sales_col, gains_col, losses_col)
# Note: "Japanese local government bonds" present in PDF but NOT in config — skip
ASALSECSOLD_LABELS = [
    ('Bonds',                    'SAL.BOND.Q',           'GAIN.BOND.Q',           'LOS.BOND.Q'),
    ('Japanese government bonds','SAL.BOND.JGOVBOND.Q',  'GAIN.BOND.JGOVBOND.Q',  'LOS.BOND.JGOVBOND.Q'),
    ('Japanese corporate bonds', 'SAL.BOND.JCORBOND.Q',  'GAIN.BOND.JCORBOND.Q',  'LOS.BOND.JCORBOND.Q'),
    ('Stocks',                   'SAL.STOCK.Q',          'GAIN.STOCK.Q',          'LOS.STOCK.Q'),
    ('Foreign securities',       'SAL.FORSEC.Q',         'GAIN.FORSEC.Q',         'LOS.FORSEC.Q'),
    ('Foreign bonds',            'SAL.FORSEC.FORBOND.Q', 'GAIN.FORSEC.FORBOND.Q', 'LOS.FORSEC.FORBOND.Q'),
    ('Other foreign securities', 'SAL.FORSEC.OTHER.Q',   'GAIN.FORSEC.OTHER.Q',   'LOS.FORSEC.OTHER.Q'),
    ('Other securities',         'SAL.OTHER.Q',          'GAIN.OTHER.Q',          'LOS.OTHER.Q'),
]

# ── Currency-related derivatives — label → (contract_col, fairval_col) ────────
# Extracted from "Fair value hedge accounting" / "Forward foreign exchange" section
CURRELDER_LABELS = [
    ('Sold',                'CURRELDER.CONTR.SOLD.Q',       'CURRELDER.FAIRVAL.SOLD.Q'),
    ('U.S. dollars',        'CURRELDER.CONTR.SOLD.USD.Q',   'CURRELDER.FAIRVAL.SOLD.USD.Q'),
    ('Euros',               'CURRELDER.CONTR.SOLD.EUR.Q',   'CURRELDER.FAIRVAL.SOLD.EUR.Q'),
    ('Australian dollars',  'CURRELDER.CONTR.SOLD.AUD.Q',   'CURRELDER.FAIRVAL.SOLD.AUD.Q'),
    ('Other',               'CURRELDER.CONTR.SOLD.OTHER.Q', 'CURRELDER.FAIRVAL.SOLD.OTHER.Q'),
    ('Total',               'CURRELDER.CONTR.TOTAL.Q',      'CURRELDER.FAIRVAL.TOTAL.Q'),
]

# ── Interest rate-related derivatives — label → (contract_col, fairval_col) ───
# "Total" rows per hedge accounting method
INTRATEDER_LABELS = [
    ('Deferred hedge accounting',                       'INTRATEDER.CONTR.DEFHEDGE.Q',    'INTRATEDER.FAIRVAL.DEFHEDGE.Q'),
    ('Exceptional treatment for interest rate swaps',   'INTRATEDER.CONTR.EXCTREATINT.Q', 'INTRATEDER.FAIRVAL.EXCTREATINT.Q'),
]

# ── Assets held-to-maturity in trust — label → col_suffix (book value column) ─
AHELDMAT_LABELS = [
    ('Assets held-to-maturity in trust',    'AHELDMAT.BOOK.AHELDRES.Q'),
    ('Assets held for reserves in trust',   'AHELDMAT.BOOK.OTHERMONHELD.Q'),
    ('Other money held in trust',           'AHELDMAT.BOOK.AHELDTOM.Q'),
]

# ── Period parsing — report title → YYYY-Q# ───────────────────────────────────
# Month-end → calendar quarter
MONTH_TO_QUARTER = {3: 1, 6: 2, 9: 3, 12: 4}
